version: '3'
services:           
  mysql:
    image: mysql:5.7
    # volumes:  
    #   - "./mysql-data:/var/lib/mysql"  
    environment:
      MYSQL_ROOT_PASSWORD: root
  app:
    build: .
    volumes:
      - "./:/app"
    ports:
      - "3000:3000"
    tty: true
    working_dir: "/app"
